sudo: required
services:
  - docker

before_install:
  - docker build -t duc56/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true duc56/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Demo CI Elastic Beanstalk"
  env: "DemoCIElasticBeanstalk-env"
  bucket_name: "elasticbeanstalk-us-east-1-198494521496"
  bucket_path: "DemoCIElasticBeanstalk"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secure_key_id: $AWS_SECRET_KEY
  secret_access_key: $AWS_SECRET_KEY